apiVersion: v1
kind: Service
metadata:
  name: {{ include "st-chart.fullname" . }}
  labels:
    {{- include "st-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.https.enabled }}
    - port: {{ .Values.service.https.port }}
      targetPort: https
      protocol: TCP
      name: https
    {{ end }}
  selector:
    {{- include "st-chart.selectorLabels" . | nindent 4 }}
